### ISSUE TITLE
Finish IOKollectMonadErrorInstance implementation

### ISSUE THREAD

**Issue by fedefernandez** [47deg/kollect#7]
Implement the `runQuery` method in `arrow.effects.IOKollectMonadErrorInstance` 

Located at: `kollect/arrow/instances/effects/instances.kt`

Also, as part of this ticket, we should remove the `TryKollectMonadErrorInstance`, because we need support for "async" operations.

**Comment by raulraja** [comment]
@fedefernandez if your interpreter targets `arrow.effects.Effect` you get `IO`, `ObservableK` and `DeferredK` for free. Kollect would have to include two separate modules for Kotlin coroutines and for Rx2 Observables beside core so people get the right dependencies when they want to target their framework of choice.

**Comment by fedefernandez** [comment]
Good to know @raulraja, I've updated the ticket #5. Does it make sense?

**Comment by fedefernandez** [comment]
I guess this is not valid anymore, @JorgeCastilloPrz could you confirm? feel free to close it.

**Comment by JorgeCastilloPrz** [comment]
Yep, the redesign I'm working on will take care about this, we can close this one. It's a bit frozen atm since we depend on a couple of things still not implemented in `Arrow` but we're working on that.
